#INCLUDE 'TOTVS.CH''
#INCLUDE 'PROTHEUS.CH'

/*/{Protheus.doc} User Function zMsAdvsize
  Aprendendo a usar a funcao MsAdvsize no qual pegará automaticamente o tamanho da tela
  @type  User Function
  @author Sidney Santos
  @since 13/11/2020
  @version 1.0
  @see https://efacildemais.blogspot.com/2011/06/msadvsize-dimensionamento-de-janelas-no.html
  @see https://tdn.totvs.com.br/display/tec/Construtor+TDialog%3ANew
  @see https://tdn.totvs.com.br/display/tec/Construtor+TSay%3ANew
  @see https://tdn.totvs.com.br/display/tec/Construtor+TButton%3ANew
  @see https://tdn.totvs.com.br/display/tec/Activate
  /*/
User Function zMsAdvsize()
   
  Local oDlgTela 
  Local cTituloJanela := 'Utilitários do Protheus'

  Local oLblClientes
  Local oLblFornecedores
  Local oLblBancos
  Local oLblProdutos
  Local oLblSize

  Local oBtnClientes
  Local oBtnFornecedores
  Local oBtnBancos
  Local oBtnProdutos
  Local oBtnFechar

  // Funcao interna que retorna um array com as coordenadas/dimensoes da tela
  Local aSize       := MsAdvsize()

  Local cSize1, cSize5, cSize6, cSize7

  cSize1            := cValToChar(aSize[1])
  cSize5            := cValToChar(aSize[5])
  cSize6            := cValToChar(aSize[6])
  cSize7            := cValToChar(aSize[7])


  oDlgTela          := TDialog():New(aSize[7],aSize[1],aSize[6],aSize[5],cTituloJanela,,,,,CLR_BLACK,CLR_WHITE,,,.T.)
  
  oLblClientes      := TSay():New(015, 015,{||'Aperte no botão para acessar o Cadastro de Clientes'},oDlgTela,,oFont,,,,.T.,CLR_RED,CLR_WHITE,200,20)  
  oBtnClientes      := TButton():New( 025, 025, "Clientes",oDlgTela,{||Mata030()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )

  oLblFornecedores  := TSay():New(040, 030,{||'Aperte no botão para acessar o Cadastro de Fornecedores'},oDlgTela,,oFont,,,,.T.,CLR_BLUE,CLR_WHITE,200,20)
  oBtnFornecedores  := TButton():New( 050, 050, "Fornecedores",oDlgTela,{||Mata020()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )

  oLblBancos        := TSay():New(065, 065,{||'Aperte no botão para acessar o Cadastro de Bancos'},oDlgTela,,oFont,,,,.T.,CLR_GREEN,CLR_WHITE,200,20)
  oBtnBancos        := TButton():New( 075, 075, "Bancos",oDlgTela,{||Mata070()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )

  oLblProdutos      := TSay():New(090, 090,{||'Aperte no botão para acessar o Cadastro de Produtos'},oDlgTela,,oFont,,,,.T.,CLR_BLACK,CLR_WHITE,200,20)
  oBtnProdutos      := TButton():New( 100, 100, "Produtos",oDlgTela,{||Mata010()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )

  oBtnFechar        := TButton():New( 125, 125, "Fechar",oDlgTela,{||oDlgTela:End()}, 40,10,,,.F.,.T.,.F.,,.F.,,,.F. )

  oLblSize      := TSay():New(160, 160,{|| cSize7 + '     ' + cSize1 + '   ' + cSize6 + '   ' + cSize5 },oDlgTela,,oFont,,,,.T.,CLR_BLACK,CLR_WHITE,200,20)

  oDlgTela:Activate(,,,)

Return 
